/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/G52tfjka88S
 */
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function SignUp() {
  return (
    <div className="flex items-center min-h-screen px-6">
      <div className="w-full py-12 lg:py-24">
        <div className="flex flex-col items-center space-y-4">
          <h1 className="text-3xl font-bold">Create an account</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Already have an account?
            <Link className="underline" href="#">
              Sign in
            </Link>
          </p>
        </div>
        <div className="grid max-w-sm gap-4 px-4 mx-auto lg:max-w-2xl lg:grid-cols-2 lg:gap-8">
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">Username</Label>
              <Input id="username" placeholder="Enter your username" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                placeholder="Enter your email"
                required
                type="email"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                placeholder="Enter your password"
                required
                type="password"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="confirm-password">Confirm Password</Label>
              <Input
                id="confirm-password"
                placeholder="Enter your password"
                required
                type="password"
              />
            </div>
            <Button className="w-full">Sign Up</Button>
          </div>
          <div className="flex flex-col justify-center space-y-4">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {/* eslint-disable-next-line */}
              By clicking the "Sign Up" button, you agree to our
              <Link className="underline" href="#">
                Terms of Service
              </Link>
              and
              <Link className="underline" href="#">
                Privacy Policy
              </Link>
              .
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
